### PR TITLE
Add installation script

### PR DESCRIPTION
**Pull request by feschber**
This script overrides all svg files in /usr/share/icons/*
with their counter parts from this repository.

### CODE REVIEW

**Review by karelbasta — CHANGES_REQUESTED** [review]
I would not specify that the install.sh script does everything automatically, as it only moves files without creating entry in theme index. Not talking about it only moving svgs to /usr/share/icons and not to the theme which user want to use the popcat indicator in. I will aprrove this script if it moves the svgs into the currently used theme and the readme only mentioning the moving part of the installation, not doing everything as it does not do the entry point installation.

**Comment by karelbasta** [comment]
Sometimes being an asshole is not the best way to live.

**Comment by feschber** [comment]
> Sometimes being an asshole is not the best way to live.

Sorry I just completely forgot about this.

**Comment by karelbasta** [comment]
I did not and decided to pull your script. I was not so nice by closing it.

**Pull request merged**
